name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # todos los días a medianoche UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake animation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: YmidOrtega
          outputs: |
            ./dist/github-contribution-grid-snake.svg
          snake_color: '#661923'             # Vinotinto
          svg_background:: '#0d1117'        # Fondo dark de GitHub
          color_snake: dark
          color_dots: '#21262d, #30363d, #c9d1d9, #f0f6fc'

      - name: Push the output to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
